server {
    listen 80 default_server;
    server_name _;

    # Logging for debugging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log info;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /comtrade-api/ {

        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:4200' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        add_header 'Access-control-allow-headers' 'Authorization, X-Api-Key, Content-Type, baggage, sentry-trace' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        if ($request_method = 'OPTIONS') {
                 add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:4200' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        add_header 'Access-control-allow-headers' 'Authorization, X-Api-Key, Content-Type, baggage, sentry-trace' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Max-Age' 1728000 always;
            add_header 'Content-Type' 'text/plain; charset=utf-8' always;
            add_header 'Content-Length' 0 always;
            return 204;
        }

        # Add CORS headers to the actual proxied responses


        proxy_pass https://pgapi.betaki.bet.br/api/;
        proxy_pass_request_body on;
        proxy_set_header Content-Type $content_type;
        proxy_set_header Host pgapi.betaki.bet.br;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header X-Api-Key $http_x_api_key;
        proxy_set_header Authorization $http_authorization;

        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }

    client_max_body_size 25M;
    sendfile on;
}